export const STRINGS = {
  // Navigation & Headers
  CLEARANCE_PROTOCOL: 'CLEARANCE_PROTOCOL_V4.0',
  ENGINE_CONFIGURATION: 'ENGINE_CONFIGURATION_V4.2',
  MONTE_CARLO_ENGINE: 'QUANTMIND // MONTE_CARLO_ENGINE_V4.2 // CLUSTER_ALPHA',
  
  // Simulation Models
  MODEL_GBM: 'Standard (GBM)',
  MODEL_FAT_TAILS: 'Fat Tails (t-dist)',
  MODEL_JUMP_DIFFUSION: 'Black Swan (Jump)',
  MODEL_REGIME_SWITCHING: 'Regime Shift (Markov)',
  DESC_GBM: 'GEOMETRIC_BROWNIAN_MOTION',
  DESC_FAT_TAILS: 'COV_ADJUSTED_EXTREME_PROBABILITY',
  DESC_JUMP_DIFFUSION: 'MERTON_JUMP_DIFFUSION_MODEL',
  DESC_REGIME_SWITCHING: 'MARKOV_REGIME_SWITCHING_LOGIC',
  
  // Gating & Auth
  POWER_SHIFT_AVAILABLE: 'POWER_SHIFT_AVAILABLE',
  USE_POWER_SHIFT: 'USE_POWER_SHIFT',
  LIMIT_REACHED: 'LIMIT_REACHED',
  CURRENT_LEVEL: 'CURRENT_LEVEL',
  UPGRADE_NOW: 'UPGRADE_NOW',
  
  // Status Messages
  COMPUTE_READY: 'COMPUTE_READY',
  ESTABLISHING_BRIDGE: 'ESTABLISHING_SECURE_BRIDGE...',
  GATEWAY_ERROR: 'GATEWAY_ERROR: Handshake failed.',
  
  // Dashboard & Navigation
  TERMINAL_DASH: 'TERMINAL_DASH',
  SYSTEM_ACTIVE: 'SYSTEM_ACTIVE',
  TOTAL_CAPITAL_ALLOCATION: 'TOTAL_CAPITAL_ALLOCATION',
  ACTIVE_PORTFOLIOS: 'ACTIVE_PORTFOLIOS',
  CORE_MODULES: 'CORE_MODULES',
  REAL_TIME_FEED: 'REAL_TIME_FEED',
  STATION: 'STATION',
  ASSET_MGMT: 'ASSET_MGMT',
  VAULT: 'VAULT',
  ASSET_HOLDINGS: 'ASSET_HOLDINGS',
  STRAT: 'STRAT',
  MODEL_BUILDER: 'MODEL_BUILDER',
  MODEL: 'MODEL',
  SIM_ENGINE: 'SIM_ENGINE',
  ORACLE: 'ORACLE',
  AI_ASSISTANT: 'AI_ASSISTANT',
  SIM_COMPLETE: 'SIM_COMPLETE',
  ACCESS_RESULTS_DATA_STREAM: 'ACCESS_RESULTS_DATA_STREAM',
  WAITING_FOR_DATA_INPUT: 'WAITING_FOR_DATA_INPUT...',
  
  // Portfolio Management
  INSTITUTIONAL_VAULT: 'INSTITUTIONAL_VAULT',
  PORTFOLIOS: 'PORTFOLIOS',
  TOTAL_CAPITAL: 'TOTAL_CAPITAL',
  ACTIVE_NODES: 'ACTIVE_NODES',
  ENGINE_IDLE: 'ENGINE_IDLE',
  LAST_SYNC: 'LAST_SYNC',
  NO_ACTIVE_NODES: 'NO_ACTIVE_NODES',
  INIT_NEW_CONSTRUCT: 'INIT_NEW_CONSTRUCT',
  STRATEGY_UID: 'STRATEGY_UID',
  IDENTIFIER: 'IDENTIFIER',
  ASSET_PROVISIONING: 'ASSET_PROVISIONING',
  WEIGHT_CALIBRATION: 'WEIGHT_CALIBRATION',
  READY: 'READY',
  PENDING: 'PENDING',
  INITIALIZE_STRATEGY: 'INITIALIZE_STRATEGY',
  
  // Asset Station
  ACCESS_DENIED: 'ACCESS_DENIED',
  UPGRADE_ACCOUNT: 'UPGRADE_ACCOUNT',
  ASSET_DISCOVERY: 'ASSET_DISCOVERY',
  MONITORED_ASSETS: 'MONITORED_ASSETS',
  NO_ASSETS_IN_WATCHLIST: 'NO_ASSETS_IN_WATCHLIST',
  
  // Simulation Results
  CONVOLVING_PATHS: 'CONVOLVING_PATHS...',
  INITIALIZING_COMPUTE: 'INITIALIZING_COMPUTE...',
  KERNEL_PANIC: 'KERNEL_PANIC',
  REBOOT_SESSION: 'REBOOT_SESSION',
  COMPUTE_REPORT: 'COMPUTE_REPORT // V4.2',
  SIM_RESULTS: 'SIM_RESULTS',
  COMPUTE_SETUP: 'COMPUTE_SETUP',
  
  // Trial Reward
  REWARD_AVAILABLE: 'REWARD_AVAILABLE',
  CLAIM_PLUS_TRIAL: 'ACTIVATE_14D_PLUS_CLEARANCE',
  TRIAL_PROMOTION: 'TRIAL_PROMOTION',
};
